docs/git-workflow.md

- **Simpler convention for commit messages used to merge from `dev` to `master`:** just use `[TESTED] <commit message that was used to merge from the secondary branch to dev>`, e.g.:
- **Added another best practice to the PR convention**: "(If applicable) Reference the issues that your PR solves using `#<number-of-issue>` (GitHub will add a link to it)."

Styleguide update

---

src/components/Sidebar.vue

Resizes the UPchieve logo on the dashboard.

Fix dashboard UPchieve logo

---

index.html
src/components/Quiz.vue
src/components/Sidebar/UserNav.vue
src/router.js

Adds a dependency on MathJax to render mathematical notation more
legibly.
Use:
- `\[ ... \]` for block math
- `\( ... \)` for inline math
TODO:
after updating question text to:
```
Evaluate the following: \(  -6^2 + 4 \cdot 3^2  \)
```
Resolves: https://app.asana.com/0/775116702697292/1115872002804915

Add MathJax rendering to certification quizzes

---

build/build.js

Display environment name correctly in build script

---

src/components/Calendar.vue

Asana: https://app.asana.com/0/1115766615375295/1115439483057742
Fixes https://github.com/UPchieve/web/issues/69
- Use async/await to fetch user's availability, which resolves the promise before continuing in the component's lifecycle. The bug was caused by a race condition where the `CalendarService.getAvailability` method often wouldn't resolve immediately.
- Only show the timezone selector & schedule once the user's availability has loaded.
This is just a quick fix. I don't think we generally want to delay the Vue lifecycle hooks and wait for data to load. Instead, we should show some default data and/or a loading state until async data has loaded.

Fix calendar rendering

---

src/components/Dashboard.vue

https://app.asana.com/0/775116702697292/1114219095361199
- Added disabled `<option>` tags to the topic and subtopic `<select>`s.
- Set the subtopic `<select>` to be disabled until the topic has been selected.
- Set the "Get help" button to be disabled until the subtopic has been selected.
- Added a watch callback to reset `pickedSubtopic` whenever `pickedTopic` is changed.
- Added a CSS rule for disabled buttons to prevent color change on hover.

Disable "Get Help" button until form is complete

---

src/components/Registration/VolunteerSignupForm.vue

Links
-----
Task: https://www.notion.so/upchieve/Phone-number-regex-validation-crashes-Firefox-other-non-Chrome-browsers-2627c2779fdd41feba76fdd3750fc117
Related PRs: https://github.com/UPchieve/web/pull/171 (original validation PR)
Description
-----------
My regex for validating U. S. phone numbers included a named capturing group. This is an ES2018 feature that is not supported in all browsers, and browsers that don't support it yet (such as Firefox) will read it as a syntax error and crash. This PR removes the named capturing group and replaces it with an ordinary capturing group, which is sufficient for our purposes.
In the future, we may want to install some plugins like the following, so that we can transform such features into constructs that are compatible with older browsers: …

removed named capturing group from regex

---

src/App.vue

Links
-----
Task: https://www.notion.so/upchieve/Vue-route-name-changes-cause-issues-hamburger-menu-icon-on-dashboard-99e6cf41c1ab4a1e9298f7cc141903a8
Description
------------
- Renamed route name `Dashboard` to `DashboardView` in App.vue
I performed various searches on the code base, and this is the only use of a route name.

Fix route name bug

---

src/services/OnboardingService.js

Links
-----
- Task: https://www.notion.so/upchieve/Volunteer-scheduling-system-audit-88e77bfa48bb421b8bcb3e916e38c7b7
Description
-----------
Currently, when a user clicks on the verification link for signup, the onboarding service sets `user.verified = true` but does not update the locally-stored user object. Ultimately, we would like to remove all dependence on `localStorage` for storing the user object on the client-side, but for now this PR fixes the behavior by updating the locally-stored user object after `verified = true` has been set.

Make sure user.verified is persisted in storage upon confirmation

---

src/views/SignupView/StudentForm.vue
src/views/SignupView/VolunteerForm/VolunteerSignupForm.vue

Links
-----
- Task: https://www.notion.so/upchieve/After-signup-Chrome-offers-to-save-your-login-details-Currently-it-s-not-parsing-the-correct-fiel-088307a7524a49e289ac6827b5fe0fe1
Description
-----------
When a new user proceeds to the page where they enter their first and last name, Chrome interprets the first name and last name fields as a username and password, and offers to save the username and password. It saves the first name as the username and the last name as the password. This issue appears to be a result of the way that Chrome tries to automatically interpret text fields as username and password fields.
This PR uses HTML5's `autocomplete` attribute to try to tell the browser what kinds of data the fields actually represent. It also tries to convince Chrome of the correct …

Fix Chrome password auto-save

---

src/views/OrgSignupView.vue
src/views/TrainingView.vue

Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/161
Description
-----------
- Add support for restricting certain volunteers to math tutoring (no college counseling)
_Note_: This is a bit hacky & not generalized to allow any/all topics to be blacklisted, but:
- we're under a time crunch
- the training view needs major refactoring -- it's not worth wrestling with right now
- restrictions by coaching topic likely won't be a common demand of partner orgs in the near future

Math-Only Partner Orgs

---

package-lock.json
src/main.js
src/services/AuthService.js

Links
-----
- Task: https://www.notion.so/upchieve/Session-Controller-Twilio-service-refactor-ecd838c592db4d4a8c074713a8f2bb13
- Server repo PR: https://github.com/UPchieve/server/pull/156
Description
-----------
The passport socket.io authentication in https://github.com/UPchieve/server/pull/156, in order to work properly, requires the socket connection to be established only after authentication. This PR connects the socket when the user logs in and disconnects when the user logs out.

Connect socket only when authenticated

---

src/views/SessionView/SessionChat/index.vue
src/views/SessionView/Whiteboard.vue
src/views/SessionView/index.vue

Links
-----
- Issue: https://github.com/UPchieve/web/issues/288
Description
-----------
- Fix issue with mobile safari scrolling that caused session's header & footer to be non-sticky sometimes
- Basically, for mobile view use fixed positioning instead of absolute, and don't rely on `vh` units

Sticky header footer mobile

---

src/views/QuizView.vue

Description
-----------
- Reference MathJax library via explicit `window` instead of implied global (I'm not positive why this was a problem, but it fixed an issue on my local machine where MathJax wasn't working at all)
- Fix issue where quiz options which had MathJax expressions that were sandwiched between two sections of plain text would cause the trailing section of plain text to be appended to later quiz question options.
- e.g. if a question's "b." option was `d\( \sqrt{3} \)  and d\( \sqrt{2} \)`, all future "b." options would have "and d" appended to them.

Fix MathJax rendering issues

---

src/views/CalendarView.vue

Links
-----
- Issue: https://github.com/UPchieve/web/issues/292
Description
-----------
- The current timezone conversion logic relies on the hour of the current time in the different timezones to try to calculate the offset. However, this breaks when the calendar date is different in the different time zones. For example, on Friday, January 3, 2020 at 22:00 in California it was Saturday, January 4, 2020 at 01:00 in New York; the code would take the difference between the hours 1 - 22 = -21 and use that offset instead of the correct one (+3) to convert the availability hours.
- This PR changes the logic to use the `parse` function in the zone object to obtain the current offsets for each timezone, rather than trying to determine it from the hours. …

Fix volunteer timezone conversion

---

src/views/SessionView/Whiteboard.vue

Links
-----
- Issue: https://github.com/UPchieve/web/issues/297
Description
-----------
- Instead of simply calling `drawEnd` every time the user's mouse leaves the canvas and potentially saving a blank canvas to the server, `drawEnd` will only be called if the user was actually drawing something when the mouse left the canvas.

Only execute drawEnd on mouse leave if the user is drawing something

---

src/services/CalendarService.js
src/services/TrainingService.js
src/views/CalendarView.vue
src/views/QuizView.vue

Links
-----
Description
-----------
- The calendar and training services are updated so that they no longer send the user ID in the body of the HTTP requests.

Remove userid from calendar and quiz request bodies

---

tests/e2e/plugins/index.js
tests/e2e/support/commands.js

Links
-----
Description
-----------
- New Cypress commands `login` and `logout` are added to send the appropriate REST API requests to authenticate the test users. These commands will allow other use cases besides logging in and out to be tested in isolation.
- Vue CLI environment variables are imported into Cypress via plugins. (See https://github.com/vuejs/vue-cli/issues/2447 for the proposition to add this into the Vue CLI.)

Login and logout commands for e2e tests of authenticated views

---

src/components/App/index.vue

Links
-----
- Sentry issue: https://sentry.io/organizations/upchieve/issues/1461024444/?referrer=github_integration
Description
-----------
- The `App` component's `beforeUpdate` hook is updated so that it only tries to fetch the current session if there is an authenticated user. This will prevent unnecessary calls to `/api/session/current`.

Only fetch session if user is authenticated

---

src/views/CalendarView.vue

Links
-----
- Issue: https://github.com/UPchieve/web/issues/312
Description
-----------
- The CSS media query for `min-width: 700px` in `CalendarView` is updated so that the date/time table becomes horizontally scrollable. The `dayTimeContainer` is placed into a new `div` so that the container can be scrolled to the left to reveal the times.

Make calendar horizontally scrollable on mobile view

---

src/services/AuthService.js
src/store/modules/user.js

Description
-----------
- On logout, clear session stored in Vuex
- Previously, when switching accounts during an active session, the first account's session would briefly be displayed in the second account (i.e. the orange top-bar saying "return to active session" would show up for a few seconds)
- Not a big issue for most of our users but it caused problems with e2e tests
- Additionally, I re-organized the user Vuex actions

Clear session on logout

---

package-lock.json
src/services/CalendarService.js
src/services/NetworkService.js
src/views/CalendarView.vue

Links
-----
- Issue: https://github.com/UPchieve/server/issues/214
- Server repo PR: https://github.com/UPchieve/server/pull/218
Description
-----------
- The client is updated so that it sends the availability and timezone into the single endpoint `/api/calendar/save`, rather than sending two separate HTTP requests for the single user action of clicking "Save".

Send availability and timezone in combined API request

---

src/views/SignupView/StudentForm.vue
src/views/StudentPartnerSignupView.vue

Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/253
Description
-----------
- Handle new option (`highSchoolSignupRequired`) from student partner manifest that dictates whether high school signup is required
- Previously, there was only support for optional high school input using the `highSchoolSignup` manifest option 

Add student partner signup flow that requires high school

---

src/views/SessionView/SessionHeader.vue

Description
-----------
- The loading ellipses for when a student starts a session were not animating on mobile devices. The only reference I found related to issues with animating the `content` property is mentioned [here](https://css-tricks.com/animating-the-content-property/#article-header-id-2).  I opted for a no-js solution and instead of animating the `content` property we animate the `width` property and hide the ellipsis to make it look as if it's loading

Loading ellipsis

---

src/views/DashboardView/VolunteerDashboard/OnboardingModal.vue

Description
-----------
- Removed global styling that placed modal buttons to the center of the modal

align buttons to the right side of modals

---

src/views/DashboardView/VolunteerDashboard/ListSessions.vue

Links
-----------
- Server repo PR: https://github.com/UPchieve/server/pull/262
Description
-----------
- Test student accounts can only be viewed by admin volunteer accounts

show test accounts to admins only

---

src/components/App/index.vue

Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/288
Description
-----------
- Remove an attempt to render the session's `whiteboardUrl` (no longer used w/ Zwibbler)

Remove old whiteboard logic

---

src/views/SessionView/Whiteboard.vue

Links
-----
- Issue: https://github.com/UPchieve/web/issues/360
Description
-----------
- In the session-test file, info sometimes comes into this function as null.

Allow document-changed info to be null

---

src/views/SignupView/index.vue

Links
-----
- Issue: https://upchieve.monday.com/boards/438837796/pulses/549531540
Description
-----------
- Add `?volunteer=true` or `?student=true` to skip choosing user type (or `=1`, `=yes`, any string)

Query params on signup route for user type

---

src/views/DashboardView/StudentDashboard/SubjectSelection/SubjectCard.vue
src/views/DashboardView/StudentDashboard/SubjectSelection/index.vue

Links
-----
- Issue: https://github.com/UPchieve/web/issues/396
Description
-----------
- A new property, `isTutoringCard`, is created to distinguish cards that are for starting tutoring sessions from cards that are for other purposes (like giving feedback). Only tutoring cards will now be disabled.

Disable only cards for starting tutoring sessions

---

src/views/DashboardView/VolunteerDashboard/ListSessions.vue
src/views/SessionView/index.vue

Description
-----------
- Don't prefer polling for waitlist
- the version of vue-socket.io we have requires a 1.x version of socket.io-client, which is apparently mostly compatible with the 2.x server-side socket.io we have, besides
> it only (partly) breaks polling transport, so you can mix 1.x and 2.0 versions with websocket transport (which is the protocol used in the vast majority of cases)
- https://github.com/socketio/socket.io/issues/3007#issuecomment-336825918
- The versioning issues are addressed in these PRs
- https://github.com/UPchieve/web/pull/413
- https://github.com/UPchieve/server/pull/351

don't prefer polling

---

.github/workflows/e2e_tests.yml

Links
------------
- You can test this with my [proof of concept](https://github.com/UPchieve/web/pull/423) without using many workflow minutes nor waiting too long for your test.
Description
-----------
- This change addresses the issue of submitting changes to both the server repo and the web repo, which must both be merged to pass Cypress integration tests. It institutes the following conditional workflow:
1. IIF A branch exists in [UPchieve/server](https://github.com/UPchieve/server) with the same name as the web branch you are merging, use that branch instead of master to run the Cypress CI tests.
1. Else, use the master branch to run the Cypress CI tests.

use corresponding server branch

---

src/router.js
src/views/LoginView.vue
src/views/ResetPasswordView.vue
src/views/SignupView/StudentForm.vue
src/views/SignupView/VolunteerForm/CodeForm.vue
src/views/SignupView/VolunteerForm/VolunteerSignupForm.vue
src/views/SignupView/VolunteerForm/index.vue
src/views/SignupView/index.vue
src/views/StudentPartnerSignupView.vue
src/views/VolunteerPartnerSignupView.vue
tests/e2e/specs/signup-tests.js

Description
-----------
- Indicate signup step in URL using optional params: `/sign-up/:userType?/:step?`
- To avoid overlap between the partner signup routes and open signup routes, route open signup through `/sign-up` instead of `/signup`
- (because `/signup/student/partnerName` can't be distinguished from `/signup/student/stepName`)
- Other options were:
- move partner signup to `/signup/partner/student/partnerName` (would have to change partner links though)
- for open signup, use the pattern `/signup/open/student/stepName` (moving to `sign-up` seemed simpler though)
- Redirect from `/signup` to `/sign-up`

Signup routes

---

.env.production
.env.staging
vue.config.js

Description
-----------
- For prod and staging, don't hit socket.io on server port 3001 (nginx now handles redirecting `host:443/socket.io/` to `localhost:3001/socket.io/`

Socket port

---

tests/e2e/specs/profile-tests.js

Links
-----
- Issue: https://github.com/UPchieve/web/issues/438
Description
-----------
I'm adding e2e tests for user profiles. These tests verify that:
* Users can update their phone number
* Users can't enter an invalid phone number
I ran into a documented issue with Cypress where it isn't properly scrolling an element into view. This issue is being tracked at: https://github.com/cypress-io/cypress/issues/871. I forced a few actions to work around this, but there are some additional workaround options suggested on the issue page. 

Add e2e tests for user profile

---

src/views/SessionView/Whiteboard.vue

Description
-----------
- Fixes "Cannot read property 'removeEventListener' of null" issue - `document.querySelector` returned null in the `destroyed` and `beforeDestroy` lifecycle hook - replaced with refs

use $refs instead of querySelector

---

src/views/Admin/AdminReports.vue

Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/444
Description
-----------
- Remove overflow hidden from the container that cut off the partner site dropdown

remove overflow that cuts off drop down

---

src/views/SessionView/index.vue

Description
-----------
- Fixed "Cannot read property 'click' of null" on ` document.querySelector(".upload-photo").click();` by adding missing `isVolunteer` getter

add isVolunteer getter

---

src/components/App/AppModal/ModalTemplate.vue
src/components/App/AppModal/index.vue
src/views/SessionView/SessionFulfilledModal.vue

Description
-----------
- If the modal component is `SessionFulfilledModal` don't allow users to close the modal by clicking outside of it
- Removed the `back` button for `SessionFulfilledModal`. Noticed that in mobile mode a user can press `back` on the modal and still land on the whiteboard when receiving the "session fulfilled message"

Fix session modal close

---

src/components/Admin/SessionListItem.vue
src/views/Admin/VolunteerCoverage.vue

Description
-----------
- Temporary fix for old sessions that have `algebra` and `calculus` as their subtopic
Note: a better fix might be a migration of those old sessions to `algebraOne` and `calculusAB`, but don't know how many other scripts are dependant on the sessions showing those subtopics

Fix topic display name

---

src/components/Admin/SessionListItem.vue

Description
-----------
- A migration has changed subtopics on Feedback and Session collections from `algebra` -> `algebraOne` and `calculus` -> `calculusAB` so no need for the display names for `algebra` and `calculus` anymore

remove display name for old subtopics on sessions

---

src/views/DeactivateAccountModal.vue
src/views/ProfileView.vue

Description
-----------
- Show a modal to confirm that a user wants to deactivate their account before the toggle button is set to deactivated

show modal when user is deactivating their account

---

src/views/SignupView/StudentForm.vue

Description
-----------
- When no school is selected or when a school that isn't listed in the `autocomplete` component is submitted, it sets `this.eligibility.highSchool` to `undefined`. This fixes PR a TypeError that appears when trying to access `upchieveId` of `undefined`

return empty object if school is undefined

---

src/views/SessionView/Whiteboard.vue

Description
-----------
- When a student presses undo after a volunteer has deleted a photo that the student has uploaded, it would cause the whiteboard to crash throwing an error in Zwibbler. This PR works around that by clearing the undo stack after a photo has been deleted so that no user can undo the deletion
Steps to test:
1. Start a session and join in as a volunteer
2. Student - upload a photo
3. Volunteer - select and delete the photo
4. Should be unable to undo the photo deletion on both volunteer and student side

workaround for Zwibbler photo deletion wb crash

---

.env.production
.env.staging
src/views/Admin/AdminSessionDetail.vue
src/views/SessionView/Whiteboard.vue

Description
-----------
- Upgraded whiteboard to the most recent Zwibbler release
- Added a "failed to load whiteboard" error message on the admin session page
- Removed clearing the undo stack when deleting a photo. The new Zwibbler update fixes the whiteboard crash that happens after undoing a photo deletion
**Whiteboard:**
1. Start a session as a student
2. Join in as a volunteer
3. Try all tools on the whiteboard
4. Upload a photo as a student
5. Delete photo as volunteer
6. Press undo as a student 
7. Whiteboard should still work properly
8. Repeat for mobile web
**Admin:**
1. Log into an admin volunteer account 
2. Click `Admin` on the sidebar
3. Click `Sessions`
4. Click on an older session that used the old whiteboard format
5. Should see an error message saying that the …

Upgrade whiteboard

---

src/components/App/index.vue

Description
-----------
- `xhr poll error`s are handled internally, we don't need to send them to Sentry. This catches those specific errors and ignores them.

ignores xhr poll error messages

---

src/components/App/index.vue

Description
-----------
- Added ignore `xhr poll error` and `web socket error` in more socket error listeners

ignore xhr poll error & socket error in other socket error listeners

---

.github/workflows/e2e_tests.yml
src/components/App/index.vue

Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/516
Description
-----------
- GitHub actions deprecated and disabled the `set-env` command - https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

move from now deprecated set-env

---

src/views/ProfileView.vue

Description
-----------
- Use e164 format on component created to avoid accidentally storing international phone number format for a user 

use e164 format instead of international

---

src/views/Admin/AdminReports.vue

Description
-----------
- student partner org must be selected before accessing `displayName`

student partner org must be selected before accessing property

---

src/views/SessionView/Whiteboard.vue
src/views/SessionView/index.vue

Description
-----------
- moved `openFileDialog` out from `Whiteboard.vue` to its parent component
- Fixes error `undefined is not an object (evaluating 'this.$refs.whiteboard.openFileDialog')`

moved openFileDialog to SessionView parent component

---

src/views/SessionView/index.vue

Description
-----------
- Pass in a missing abort function to `showTroubleStartingModal` 
- Fixes error `this.modalData.abortFunction is not a function`

pass in missing abort fn to showTroubleStartingModal

---

src/services/AuthService.js

Description
-----------
- Fixes errors: `Cannot read property 'upchieve101' of undefined` and `undefined is not an object (evaluating 'this.certifications[this.course.quizKey]')`. When a user clicks "logout" from `TrainingView` the component gets rendered without a `user` object in the vuex store and throws the two errors mentioned. This fix first does the redirect to `/logout` and then removes the user from vuex

switch order of logout methods
