UPchieve/web

src/components/TempProfile.vue
established some standards: 50px from left, 40x from top, checklists
indented, short response line length, etc.
=> styled name through race profile fields

src/assets/calendar_icon-01.svg, src/assets/college_icon-01.svg, src/assets/contact_us_icon-01.svg, src/assets/home_icon-01.svg, src/assets/log_out_icon-01.svg, src/assets/math_icon-01.svg, src/assets/privacy_policy_icon-01.svg, src/assets/resources_icon-01.svg, src/components/Sidebar/Footer.vue, src/components/Sidebar/UserNav.vue
=> Sidebar icons

src/components/Sidebar/Footer.vue, src/components/Sidebar/UserNav.vue
=> Fixed alignment of log in button

src/components/Dashboard.vue
When the user clicks 'Get help from a tutor' button they are asked to select a topic and a then subtopic, then when they click 'Get help' it takes them to the topic's whiteboard page where they wait for a tutor.
=> Select help topic

src/components/Onboarding.vue, src/components/Onboarding/Academic.vue, src/components/Onboarding/Profile.vue, src/services/OnboardingService.js
UX styling for the onboarding process (excluding login, logout and reset password)
=> Onboarding UX

src/components/Onboarding/Profile.vue
can potentially work on backend stuff for this later this weekend
=> change front end options

src/components/Sidebar/ProfileInfo.vue
Said "undefined undefined" before, now will say "Welcome, Student/Volunteer!" until they are done with onboarding.
=> Fix name under photo

src/components/Sidebar/ProfileInfo.vue
no more auth, using v-else instead of v-else-if, and also show Welcome Student/Volunteer with path  signup
=> fixes to name under profile pic

src/components/Onboarding/Academic.vue, src/components/Onboarding/Profile.vue, src/components/Profile.vue, src/components/Sidebar/ProfileInfo.vue, src/services/OnboardingService.js, src/services/UserService.js
Student and volunteer onboarding and profiles, with the exception of a few features, which are commented on in the google docs below:
https://docs.google.com/document/d/1SxCRd5MUxqrerd1EFoW45eT0KRxSvDO6FXzwGX-UnVM/edit
https://docs.google.com/document/d/1Mf4SwPtVmCYMDawpjGPPxbYsnNJgu0zOhB9lhVSpxZ0/edit
=> Onboarding updates

src/components/Profile.vue
=> Make text notifications optional - rev #01

src/components/Profile.vue
=>  Allow edit of email address from Profile

src/assets/styles/settings.css, src/components/Legal.vue, src/components/atoms/ContentHeader.vue, src/components/molecules/AccordionItem.vue, src/components/organisms/Accordion.vue, src/components/organisms/FullTextTemplate.vue, src/main.js
@alysamurray Done :heavy_check_mark: :blush:
=> Legal redesign

src/components/Training.vue, src/services/AuthService.js, src/services/UserService.js
@WAftring We had the issue because `UserService.getUser()` gets the data from Local Storage instead of getting it directly from the end point.
I created a new method (`UserService.fetchUser()`) to be used when we need to access the user's data directly from the API, and also tidied things up a little bit :blush:.
=> Solved bug, added a fetchUser() method to UserService

src/components/Quiz.vue, src/components/Training.vue
@WAftring Done :v:
Edits in `src/components/Training.vue`:
- Removed "essay" and "application"' from the list of quizzes because it causes an error due to a mismatch with the schema
Edits in `src/components/Quiz.vue`:
- Added a call to `UserService.fetchUser()` inside `beforeMount()` to make sure that the view displays the updated number of tries
- Tidied things up here and there :blush:
=> :tada: Fixed issues in Training and Quiz components

src/components/Quiz.vue, src/components/Training.vue
=> Revert ":tada: Fixed issues in Training and Quiz components"

src/components/Resources.vue
=> Fixed Resources Page CSS/HTML

src/App.vue, src/components/LoginForm.vue, src/components/Logout.vue, src/components/Onboarding/Academic.vue, src/components/Onboarding/Profile.vue, src/components/Registration.vue, src/components/Registration/SignupForm.vue, src/components/ResetPasswordForm.vue, src/components/Sidebar/Footer.vue, src/components/Sidebar/ProfileInfo.vue, src/components/Sidebar/UserNav.vue
=> Revert "Hide sidebar on logged-out pages"

src/App.vue, src/components/LoginForm.vue, src/components/Logout.vue, src/components/Onboarding/Academic.vue, src/components/Onboarding/Profile.vue, src/components/Registration.vue, src/components/Registration/SignupForm.vue, src/components/ResetPasswordForm.vue, src/components/Sidebar/Footer.vue, src/components/Sidebar/ProfileInfo.vue, src/components/Sidebar/UserNav.vue
=> Revert "Revert "Hide sidebar on logged-out pages""

package-lock.json, src/components/Dashboard.vue, src/components/ListSessions.vue
Fixed dynamic url
Fixed Subtopic not showing
Removed ESL from available subjects
=> Various fixes

src/components/Contact.vue, src/components/Legal.vue, src/components/LoginForm.vue, src/components/Registration.vue, src/components/Registration/CodeForm.vue, src/components/Registration/SignupForm.vue
=> Added links at the bottom of log-in/registration pages to match wireframes

package-lock.json, src/components/Dashboard.vue, src/components/ListSessions.vue, src/components/Session/Chat.vue
Changed variable name from result to results in code that checks for college being topic.
=> Fixed bug with college subtopics not showing up for volunteer.

package-lock.json, src/components/Dashboard.vue, src/components/ListSessions.vue, src/components/Session/Chat.vue
=> Revert "Fixed bug with college subtopics not showing up for volunteer."

package-lock.json, src/components/Registration/StudentForm.vue, src/components/Registration/VolunteerSignupForm.vue
1. Added question 'Do you get help from any of these organizations' for students during registration
2. Added phone number for volunteers during registration
3. After volunteers successfully signed up, show a prompt to ask volunteer to verify their email instead of showing a white box
=> bug fix for registration

src/components/LoginForm.vue, src/components/Registration/VolunteerSignupForm.vue
PR #114 was manually tested on `dev` and it integrated well :+1:
=> [TESTED] Merge pull request #114 from UPchieve/fix/chat-messages

src/components/Session/Chat.vue, src/components/Session/Header.vue, src/components/Session/Whiteboard.vue
1. Fixed issue where icons were appearing halfway down the text rather than at the top.
2. Changed timestamp at bottom of messages to just be hour and minutes (no seconds)
3. Fixed issue where if both the volunteer and the student had the same first name, all messages would appear on the left side (instead of alternating left and right)
4. Fixed issue where all icons were appearing the same (not different for volunteers and students)
=> Fixed chat box bugs

src/components/Registration/VolunteerSignupForm.vue
Fixes https://github.com/UPchieve/web/issues/120
Haven't run any test suites as it's just a small copy change.
=> Fix #120 Remove apostrophe from phone number form label

package-lock.json, package.json, src/components/Calendar.vue, src/services/CalendarService.js, src/services/NetworkService.js
This PR allows user to choose their time zone for their availability calendar.
- Create a new field in mongodb schema which records the selection of timezone of the user, added API for updating and getting timezone user selected
- If the user has never selected any timezone before, the Vue frontend will automatically detect the timezone of the user
- All the availability are saved in EST in database. These time are converted to the time zone that user selected in Vue frontend when they are displayed to user.
=> Feature/Time Zone

src/components/Registration/StudentForm.vue
Fix a typo and add a couple of question options in the student signup process.
https://upchieve.slack.com/archives/C2RMWLGK1/p1555373514000300
=> Update student signup

src/components/Session/Chat.vue
Temporarily disables CleanSpeak moderation.
cc @jkeat for vis
=> Disable CleanSpeak moderation

README.md
Links
-----
Task: Updated README with Node and NPM information. Added link to the server repo. Modified the structure of the README. 
Description
-----------
Background: Trouble building initially because of unknown NPM and Node versions. 
Added more commands for ease of use. Linked to server repo so developers can easily get the full web application up and running. 
=> Updated README to include more build info. 

src/components/Session/Chat.vue
Description
-----------
Uncommented old moderation service call; minor style changes with warning popup
=> Return chat warning when profanity/personal info is entered

src/components/Dashboard.vue, src/components/ListSessions.vue, src/components/Sidebar.vue
the sidebar should be functional and the footer/user navbar components shouldn't overlap. if there are more routes where they can't all fit on the sidebar, you can use a scrollbar (only really relevant to the volunteers).
Task: https://www.notion.so/upchieve/6abe4da08ab045eea31efb13148448d6?v=1d1d833174ef402195a1d75586a1356d&p=680d8356a92d47f2b31ebb07c409c904
=> fixed sidebar for all links to fit nicely or scroll if needed

src/components/Dashboard.vue, src/components/Legal.vue, src/components/ListSessions.vue, src/components/Registration/SignupForm.vue, src/components/Registration/StudentForm.vue, src/components/Registration/VolunteerSignupForm.vue, src/router.js
Quick one line change to remove hash (/#/) from urls.
=> Change url mode from hash to history

src/components/Onboarding/Profile.vue, src/components/Profile.vue
Links
-----
Task: https://www.notion.so/upchieve/Store-phone-number-in-format-accepted-by-Twilio-5ab9c42e48f54325aaee7fec063d1ff3
Related PRs: https://github.com/UPchieve/server/pull/99
Description
-----------
This PR ensures that the phone numbers are sent to the server correctly when the backend changes are made in https://github.com/UPchieve/server/pull/99. The changes allow the server to reformat phone numbers and store them in the database correctly for Twilio, while sending them to the client in a more readable format.
=> Format phone numbers

src/views/FeedbackView.vue
Links
-----
- Task: https://www.notion.so/upchieve/Student-feedback-form-changes-d74d7791982b4134b0bb30a1ca00a971
Description
-----------
- new content for student feedback form
- add "radio list" format for feedback form questions
=> Feedback form changes

src/views/DashboardView/VolunteerDashboard/index.vue, src/views/SessionView/SessionChat.vue
Links
-----
https://github.com/UPchieve/server/pull/129
=> Chat fixes

src/views/TrainingView.vue
server repo companion (non-dependant): https://github.com/UPchieve/server/pull/138
=> Misc housekeeping

package-lock.json, package.json, src/router.js, src/views/SessionView/index.vue
Links
-----
- Task: https://www.notion.so/upchieve/Send-notified-volunteers-a-link-to-the-session-c1aa2196964d4e67ba44a62ded6944c5
- Server repo PR: https://github.com/UPchieve/server/pull/144
Description
-----------
A new route will allow volunteers who have received a URL in the SMS message to join sessions immediately after logging in. This new URL is in a format that reduces the number of characters in the SMS message.
=> Compact URL route for session

src/views/LegalView.vue
Updating Legal Agreement w/ Volunteer Agreement
=> Rb legalupdates

package-lock.json, package.json, src/main.js, src/scss/main.scss, src/scss/setup/_overrides.scss, src/views/OrgSignupView.vue, src/views/ProfileView.vue
https://github.com/UPchieve/server/pull/147
=> Support international numbers

src/views/DashboardView/VolunteerDashboard/index.vue, src/views/SessionView/SessionChat.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/142
Description
-----------
- Don't use the user's email as the unique identifier for their messages; instead, use their user ID.
=> Clean up user population; Minimize sending the client user data

package-lock.json, package.json, src/main.js
Add a simple Sentry integration
(I'm 99% sure it's okay to commit our public API key -- it'll be sent to the client's browser anyway)
=> Basic client Sentry integration

src/views/FeedbackView.vue
Description
-----------
- Update contents of volunteer feedback form
=> Volunteer feedback form changes

src/services/AuthService.js, src/services/CalendarService.js, src/services/NetworkService.js, src/store/modules/user.js, src/views/CalendarView.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/181
Description
-----------
- The volunteer schedule page was sometimes taking a while to load, so this PR speeds it up
- Instead of separately fetching the user's timezone and availability from server endpoints, just get these from the user model that we already have loaded on the client
- Also: remove some unused calendar logic and remove `id="time"` from the schedule cell checkboxes (unused & gave warnings about duplicate element IDs
=> Schedule fix

src/views/CalendarView.vue
Links
-----
- Issue: _https://github.com/UPchieve/web/issues/299_
Description
-----------
- Added behavior which adds a checkmark to the save button when completed.
=> add checkbox for successful save (#299)

src/views/CalendarView.vue
Description
-----------
- Per discussion, adding an indication for when the data is being saved (as duration may be long).
=> Save schedule indication

src/views/FeedbackView.vue
Links
-----
- Issue: https://github.com/UPchieve/server/issues/201
Description
-----------
- "Somewhat Agree" --> "Somewhat Disagree"
=> Fix feedback form typo

src/services/AuthService.js, src/services/OnboardingService.js, src/services/SessionService.js, src/services/UserService.js, src/store/modules/user.js, src/utils/error-from-http-response.js, src/views/OrgSignupView.vue, src/views/ResetPasswordView.vue, src/views/SessionView/index.vue, src/views/SetPasswordView.vue, src/views/SignupView/StudentForm.vue, src/views/SignupView/VolunteerForm/VolunteerSignupForm.vue
Send error HTTP responses to Sentry if they are unexpected
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/188
Description
-----------
- When the server sends an HTTP response to a REST API request with an error code, the promise is rejected with the HTTP request. This PR updates the client to reflect the changes in the server repository, which cause REST API responses to be sent to the client with error codes. Error responses with unexpected status codes (e.g. 400 when it is expected that the client produce a syntactically correct request regardless of user input) are sent to Sentry.
=> Handle HTTP status codes appropriately

src/services/AuthService.js, src/views/LoginView.vue
Links
-----
- Sentry issue: https://sentry.io/organizations/upchieve/issues/1334057281/events/8cb0623c68c3438f8f4edc15005804b3/?project=1819161
Description
-----------
- Handle invalid username/password error
- Move the setting of an error message from AuthService to LoginView
=> Handle login error

src/components/App/AppSidebar/SidebarInfo.vue, src/components/App/AppSidebar/SidebarLinks.vue, src/router.js, src/services/NetworkService.js, src/views/StudentPartnerSignupView.vue, src/views/VolunteerPartnerSignupView.vue, tests/e2e/fixtures/users/partnerStudent1.json, tests/e2e/specs/student-partner-tests.js, tests/e2e/support/commands.js, tests/unit/components/App/AppSidebar/SidebarLinks.spec.js
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/212
Description
-----------
- Add quicker signup for students referred from partner organizations
- Make room for concept of "student partner orgs" by referring to existing partner orgs as explicitly volunteer-related
- Add configuration for student partner orgs to display high school field on signup
- Misc code cleanup
=> Student partner org signup

src/views/SignupView/VolunteerForm/VolunteerSignupForm.vue, src/views/StudentPartnerSignupView.vue, src/views/VolunteerPartnerSignupView.vue
Links
-----
- Issue: https://sentry.io/organizations/upchieve/issues/1461066190/?project=1819161
Description
-----------
- 422 HTTP errors are expected on signup (e.g. when password doesn't meet criteria) so don't capture these with Sentry
=> Expected 422 HTTP errors on signup

src/services/NetworkService.js, src/views/TrainingView.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/224
Description
-----------
- Added a request to `/training/review/(category)` in NetworkService
- When user clicks on "review" a request is sent to the backend to track that action
=> Viewed materials action

src/views/SessionView/SessionFulfilledModal.vue, src/views/SessionView/index.vue
Links
-----
* Server repo PR: https://github.com/UPchieve/server/pull/241
Description
-----------
- Updating the modal text to show more accurate and relevant information to how the session was ended
=> Ended session message

tests/e2e/fixtures/users/newStudent1.json, tests/e2e/fixtures/users/newVolunteer1.json, tests/e2e/specs/signup-tests.js
Links
-----
- Issue: https://github.com/UPchieve/web/issues/307
- Server repo PR: https://github.com/UPchieve/server/pull/238
Description
-----------
- End-to-end tests are created for the processes of student and volunteer signup
- For the student process, a valid high school is obtained from the server using the new `/school/findeligible` admin-only endpoint.
- For the volunteer process, a valid registration code is obtained from the server using the new `/auth/register/volunteercodes` admin-only endpoint.
- After the new volunteer signs up, the new `/api/verificationtoken` admin-only endpoint is used to obtain the token to complete the verification step.
- Failure cases are also added for ineligible high schools, invalid registration codes, and invalid verification tokens.
Developer …
=> Signup e2e tests

cypress.json, package.json, src/utils/topics.js, src/views/ProfileView.vue, tests/e2e/specs/login-tests.js, tests/e2e/specs/session-tests.js, tests/e2e/specs/signup-tests.js, tests/e2e/specs/student-partner-tests.js
Description
-----------
- Setting up Cypress to run standalone and headless
- Switched relative testing routes to absolute routes
- Remove flatMap usage (not supported by Cypress's headless browser, Electron) 
=> Cypress headless

tests/e2e/specs/availability-tests.js
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/246
Description
-----------
- Add e2e tests for volunteer availability
=> Availability e2e tests

.gitignore
Description
-----------
- Ignore Zwibbler (ahead of time)
=> Git ignore Zwibbler

src/views/VolunteerPartnerSignupView.vue
Description
-----------
- Wording dependent on whether the partner has required email domains
=> Volunteer partner signup copy

src/services/NetworkService.js, src/views/SignupView/StudentForm.vue, tests/e2e/specs/signup-tests.js
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/260
Description
-----------
- Student can sign up with an eligible zip code
TODO:
- Fix student signup e2e test(s)
=> Zip code signup

src/views/DashboardView/VolunteerDashboard/ListSessions.vue
Description
-----------
- Allow admins or test users to see sessions in waiting list from test students
=> Fix waiting list filtering of test students

src/views/ReviewMaterialsView.vue
Description
-----------
- Fix the labeling for the review materials
=> fix labeling on review material imports

src/views/CalendarView.vue
Description
-----------
- Handle fractional GMT offsets (such as Sri Lanka's GMT+5.5) by rounding the offset
=> Support fractional timezone offsets

public/index.html
adding google analytics
Links
-----
- Issue: _link to GitHub issue (or remove this line)_
- Server repo PR: _link to companion PR in server repo (or remove this line)_
- Dependency PRs: _links to PRs that must be merged prior this one (or remove this line)_
Description
-----------
- _A summary of code changes_
=> adding google analytics

src/components/AccordionItem.vue, src/services/NetworkService.js, src/store/modules/user.js, src/views/DashboardView/VolunteerDashboard/index.vue, src/views/ProfileView.vue, src/views/TrainingView.vue, tests/e2e/support/commands.js
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/278
Description
-----------
- use volunteer stats endpoint to get num hours tutored (volunteer dashboard)
- stop using these mongoose virtuals:
- `numPastSessions`
- `isOnboarded`
- `phonePretty`
- `matchCoachingOnly`
- Minor CSS cleanup
=> Handle having no User model mongoose virtuals

src/services/AuthService.js, src/views/DashboardView/VolunteerDashboard/ListSessions.vue, src/views/SessionView/index.vue
Description
-----------
- Use polling for ListSessions
- Don't connect socket on login
- Disconnect socket on ListSessions teardown
=> Socket cleanup + polling for ListSessions 

src/components/FormPageTemplate.vue, src/scss/layout/_form.scss, src/views/DashboardView/VolunteerDashboard/index.vue
Description
-----------
- Check that `user.pastSessions` exists before checking length
- Small style improvements (less padding width on mobile forms)
=> Past sessions fix

src/scss/layout/_form.scss, src/services/NetworkService.js, src/views/SignupView/StudentForm.vue, src/views/SignupView/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/308
Description
-----------
- Add new step to student signup flow that asks for a "signup code" which, if provided, directs the user to the corresponding student partner signup page
TODO:
- Remove "referred by" dropdown for student signup (no longer used)
- breaks e2e tests?
=> Student signup code

src/views/DashboardView/StudentDashboard/ReferralModal.vue
Description
-----------
- Added a transparent background on the referral input for Firefox
=> add transparent background for referral input

src/views/SignupView/index.vue
Links
-----
- Issue: https://upchieve.monday.com/boards/438837796/pulses/539633930
Description
-----------
- Allow volunteers to sign up through the mobile web
=> student only sign up flow for mobile app

src/components/FormPageTemplate.vue
Links
-----
- Issue: https://upchieve.monday.com/boards/438837796/pulses/537735808
Description
-----------
- Updated the background image to scroll with the rest of the page - this was an issue when the form was larger than the viewport - see screenshot in Monday.com for reference
New screenshot on iPhone 6s
=> removed background-attachment: fixed  on background image

src/views/DashboardView/StudentDashboard/ReferralModal.vue
Description
-----------
- Temporarily change the referral drawing day from the 1st to the 4th
=> 1st -> 4th for the referral drawing date

src/views/DashboardView/StudentDashboard/ReferralModal.vue
Description
-----------
- Changed referral drawing day from 4th to 8th
=> 4th -> 8th

src/utils/topics.js, src/views/DashboardView/StudentDashboard/SubjectSelection/index.vue, src/views/ProfileView.vue, src/views/ReviewMaterialsView.vue, src/views/TrainingView.vue, tests/unit/views/DashboardView/StudentDashboard/SubjectSelection/index.spec.js
Links
-----
- Issue: https://upchieve.monday.com/boards/438837796/pulses/544408746
- Server PR: https://github.com/UPchieve/server/pull/328
Description
-----------
- Added biology
=> Add biology

src/views/SignupView/StudentForm.vue
Links
-----
- Issue: https://upchieve.monday.com/boards/438837796/pulses/549457106
Description
-----------
- Show sign up code view only for mobile app users
=> only show sign up code page for mobile app

src/components/Admin/UserPreview.vue, src/router.js, src/services/NetworkService.js, src/views/Admin/AdminSessionDetail.vue, src/views/Admin/AdminUserDetail.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/347
Description
-----------
- show user details + past sessions
=> User detail for admin

src/views/SignupView/VolunteerForm/VolunteerSignupForm.vue, src/views/VolunteerPartnerSignupView.vue
Description
-----------
- specify *cell* phone
- clarify why we ask for it
=> Phone signup copy

src/views/Admin/AdminUserDetail.vue
Server PR: https://github.com/UPchieve/server/pull/353
=> don't reverse past sessions, expect sorted pastSessions

src/views/Admin/AdminSessionDetail.vue
Links
-----
- Issue: https://upchieve.monday.com/boards/438837796/pulses/572202143
Description
-----------
- Add who the session was ended by
=> show who the session was ended by

src/views/DashboardView/StudentDashboard/ReferralModal.vue, src/views/DashboardView/StudentDashboard/SubjectSelection/index.vue, tests/unit/views/DashboardView/StudentDashboard/SubjectSelection/index.spec.js
Description
-----------
- Updated the student referral system information
=> updated copy for referral information

src/views/DashboardView/VolunteerDashboard/ListSessions.vue
Description
-----------
- Avoid emitting "list" before connection established
- Also, don't disconnect on component destroy
=> Only emit "list" once connection established

package-lock.json, package.json, src/router.js, src/views/SessionView/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/362
Description
-----------
- Remove the short link view, which broke because of route param discrepancies
- To avoid confusion, going forward we shouldn't have multiple URL patterns that lead to the same view
=> Remove short link view

src/consts.js, src/utils/is-physics.js, src/utils/topics.js, src/views/DashboardView/StudentDashboard/SubjectSelection/index.vue, src/views/DashboardView/VolunteerDashboard/ListSessions.vue, src/views/QuizView/index.vue, src/views/ReviewMaterialsView.vue, src/views/TrainingView.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/364
Description
-----------
- Add chemistry and physics to topics
- Hide chemistry and physics from student subject selection
~~TODO: Change Physics to Physics 1~~
=> Add chemistry and physics

src/components/Admin/SessionListItem.vue, src/components/App/AppModal/ModalTemplate.vue, src/utils/is-integrated-math.js, src/utils/is-physics.js, src/utils/topics.js, src/views/DashboardView/StudentDashboard/SubjectSelection/SubjectSelectionModal.vue, src/views/DashboardView/StudentDashboard/SubjectSelection/index.vue, src/views/DashboardView/VolunteerDashboard/ListSessions.vue, src/views/TrainingView.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/363
Description
-----------
- Added Integrated Math as a selection for students
- Hide Integrated Math from Volunteers on quiz page, but show as a cert in their profile page
- Integrated Math formatting: `integratedMathOne` -> `Integrated Math 1`
=> Integrated math

src/views/DashboardView/StudentDashboard/SubjectSelection/index.vue
Description
-----------
- Add chemistry as a subject that students can request help in
=> chemistry subject selection

src/views/DashboardView/VolunteerDashboard/index.vue
Description
-----------
- Add hours of elapsed availability to the volunteer dashboard
=> added elapsed availability to dashboard

src/services/NetworkService.js, src/views/SignupView/StudentForm.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/379
Description
-----------
- Send the referral code to the server when checking if a student is eligible
=> send referral code to server

.github/workflows/e2e_tests.yml, src/components/Admin/FilterPanel.vue, src/services/NetworkService.js, src/views/Admin/AdminSessions.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/373
Description
-----------
- Added a filter panel to filter banned users, test users, by session length, number of messages sent, and session activity date range
=> Admin filter tools

src/components/Admin/IneligibleStudentListItem.vue, src/router.js, src/services/NetworkService.js, src/views/Admin/AdminIneligibleStudents.vue, src/views/Admin/AdminSchoolDetail.vue, src/views/Admin/AdminUserDetail.vue, src/views/Admin/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/380
Description
-----------
- Admins are able to see ineligible students when clicking on the "Ineligible Students" tab
- Admins can change the `isApproved` status of a school
=> Admin ineligible students v2

src/router.js
Description
-----------
- Add custom dimensions to google analytics
- Send page view on route change
=> GA dimensions

src/components/Loader.vue, src/scss/layout/_form.scss, src/views/ResetPasswordView.vue, src/views/SetPasswordView.vue
Description
-----------
- Prevent multiple submits to send off the password reset emails
- Added a loader after a user hits submit for requesting a password reset email and when a user updates their password
- Added a home link to the password reset request view for signed in users
- Added a button designating to `home` or `log in` after password update is successful
=> Update Reset Password views

package-lock.json, package.json, src/services/NetworkService.js, src/views/DashboardView/VolunteerDashboard/PhotoUploadModal.vue, src/views/DashboardView/VolunteerDashboard/ReferencesModal.vue, src/views/DashboardView/VolunteerDashboard/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/390
Description
-----------
- AWS S3 photo ID upload
=> Photo ID upload

src/store/modules/user.js, src/views/DashboardView/VolunteerDashboard/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/386
Description
-----------
- `isOnboarded` will now be property on the user
=> removed isOnboarded from vuex

public/index.html, src/router.js
Description
-----------
- use window.gtag
- https://developers.google.com/analytics/devguides/collection/gtagjs/migration#send_custom_dimensions_and_metrics
=> Fix custom dimension reporting

src/services/NetworkService.js, src/views/Admin/AdminPendingVolunteerDetail.vue, src/views/DashboardView/VolunteerDashboard/ReferencesModal.vue, src/views/DashboardView/VolunteerDashboard/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/397
Description
-----------
- Removed LinkedIn
- Moved the dropdown for photo approval to align with the title
=> Remove linkedin

src/components/App/index.vue
Description
-----------
- Capture client socket.io errors
=> capture socketio errors

src/components/Admin/NotificationPreview.vue, src/router.js, src/services/NetworkService.js, src/views/Admin/AdminSessionDetail.vue, src/views/Admin/AdminSessionNotifications.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/402
=> session notif ui

src/components/Admin/NotificationPreview.vue, src/views/Admin/AdminSessionDetail.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/403
=> Display notif priority

src/router.js
Description
-----------
- https://router.vuejs.org/guide/advanced/scroll-behavior.html
=> scroll reset

src/components/ReportsFilterPanel.vue, src/components/SchoolList.vue, src/router.js, src/services/NetworkService.js, src/views/Admin/AdminReports.vue, src/views/Admin/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/410
Description
-----------
- New view for admins to generate session and usage reports
- Added a report filter panel 
=> Admin reports

src/components/Admin/BackgroundInfo.vue, src/views/Admin/AdminPendingVolunteerDetail.vue, src/views/Admin/AdminUserDetail.vue
Links
-----
- Dependency PRs: https://github.com/UPchieve/web/pull/447
Description
-----------
- Background info displayed in regular user detail + pending volunteer detail
=> Display background info in admin

package-lock.json, package.json
Description
-----------
- Integration tests are now correctly running on the cloud, so husky git scripts are not required. Continuing to have them without expecting to use them leads to a "broken windows" problem with quality control.
=> remove_husky

src/views/BackgroundInfoView.vue, src/views/DashboardView/VolunteerDashboard/PhotoUploadModal.vue, src/views/DashboardView/VolunteerDashboard/ReferencesModal.vue, src/views/DashboardView/VolunteerDashboard/index.vue, src/views/SignupView/VolunteerForm.vue, src/views/VolunteerPartnerSignupView.vue
Description
-----------
- Changed the copy on various pages throughout the volunteer dashboard, approval process, and onboarding process. 
- Added 1 new potential status for references
=> Copy changes

src/services/NetworkService.js, src/views/Admin/AdminPendingVolunteerDetail.vue, src/views/DashboardView/VolunteerDashboard/ReferencesModal.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/424
Description
-----------
- volunteer must enter the first and last name of a reference
- referenceName -> referenceFirstName & referenceLastName
=> added referenceFirstName and referenceLastName

src/components/Admin/BackgroundInfo.vue, src/views/Admin/AdminPendingVolunteerDetail.vue, src/views/BackgroundInfoView.vue, src/views/DashboardView/VolunteerDashboard/index.vue, src/views/SignupView/VolunteerForm.vue, tests/e2e/specs/signup-tests.js, tests/e2e/specs/volunteer-dashboard-tests.js
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/423
Description
-----------
- Removed `college` and `favoriteAcademicSubject` from volunteer sign up
- Added college input field when a user clicks that they are an undergrad or grad student
- Added company field for volunteers who work full time and are not from a partner org
- Display an error message for LinkedIn link when not following the proper format
- updated background tests
=> Update bg info

src/views/Admin/AdminSessionDetail.vue
Description
-----------
- fix device platform showed
=> fix user agent accessor on this.session

src/services/NetworkService.js, src/views/SessionView/ReportSessionModal.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/426
Description
-----------
- Add reason for reporting a session
=> Session report changes

src/scss/layout/_form.scss, src/views/Admin/AdminUserDetail.vue, src/views/StudentPartnerSignupView.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/427
Description
-----------
- Add student partner sites to signup
=> Student partner sites

src/components/Admin/UserListItem.vue, src/router.js, src/services/NetworkService.js, src/views/Admin/AdminUsers.vue, src/views/Admin/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/428
Description
-----------
- Allow admins to search for a user using the user's first name, last name or email
=> allow admins to search for users

src/views/Admin/AdminSessionDetail.vue
Links
-----
- Issue: _link to GitHub issue (or remove this line)_
- Server repo PR: https://github.com/UPchieve/server/pull/429
- Dependency PRs: _links to PRs that must be merged prior this one (or remove this line)_
Description
-----------
- View the final state of the document editor for college sessions in the admin session review
=> show final doc editor state in admin session view

src/components/ReportsFilterPanel.vue, src/services/NetworkService.js, src/views/Admin/AdminEditUser.vue, src/views/Admin/AdminEditUserDetail.vue, src/views/Admin/AdminReports.vue, src/views/Admin/AdminUserDetail.vue, src/views/SessionView/Whiteboard.vue
Links
-----
- Server repo PR:https://github.com/UPchieve/server/pull/430
Description
-----------
- Added a view to edit a user's properties
- Updated styling on report page's partner org dropdown select and the high school input element
=> Admin update user

src/consts.js, src/views/SessionView/Whiteboard.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/435
Description
-----------
- Don't store images in whiteboard doc
=> Don't store images in whiteboard doc

src/services/NetworkService.js, src/views/Admin/AdminUsers.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/438
Description
-----------
- Added a drop-down for finding users by partner org
- Find users by a high school name
=> Update admin search user

src/views/SessionView/Whiteboard.vue
Description
-----------
- Fixes the issue of uploading the same image without refreshing or uploading a different image
=> reset file input

src/views/SessionView/Whiteboard.vue
Description
-----------
- Constrains on panning
- Grid overlay. todo: keep?
=> Restrict whiteboard pan

src/views/SessionView/Whiteboard.vue, src/views/SessionView/index.vue
Description
-----------
- Ensure whiteboard always has the correct session ID
=> Whiteboard session ID fixes

src/views/DashboardView/VolunteerDashboard/PhotoUploadModal.vue, src/views/SessionView/Whiteboard.vue
Description
-----------
- Let Sentry capture an error when joinedSharedSession throws one
- Changed invalid accepted file type from `image/jpg` to `image/jpeg`
=> capture joinedSharedSession error and jpg -> jpeg

src/views/StudentPartnerSignupView.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/445
Description
-----------
- Added college input for optional or required college for student partner org
=> added option for required or optional college input

src/views/SessionView/Whiteboard.vue, src/views/SessionView/index.vue
Description
-----------
- Make whiteboard read-only on session end
- Fixes issue caused by interacting with whiteboard that had been cleared from the server's doc cache
=> Read-only whiteboard on session end

src/views/VolunteerPartnerSignupView.vue
Description
-----------
- Update error message for invalid CP email domain
=> CP invalid email message

src/views/Admin/AdminEditUser.vue, src/views/Admin/AdminPendingVolunteerDetail.vue, src/views/Admin/AdminUserDetail.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/453
Description
-----------
- Allow users that are not approved to be edited and updated
=> edit unapproved volunteers

src/views/SessionView/SessionChat/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/456
Description
-----------
- Update chat warning message to show that messages cannot contain links to third party video services
=> update chat warning moderation for 3rd party video services

src/services/SessionService.js
Description
-----------
- Don't immediately clear session from vuex on session end
=> Prevent zwibbler from being initiated when ending college session

src/views/SessionView/Whiteboard.vue
Description
-----------
- Reconnect Zwibbler after disconnect
- Make read-only when disconnected
=> Reconnect Zwibbler after disconnect

package-lock.json, package.json, src/main.js, src/views/ProfileView.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/464
Description
-----------
- Volunteers can edit account status from profile i.e. toggle `isDeactivated`
=> Toggle deactivated

src/components/Admin/FeedbackPreview.vue, src/services/NetworkService.js, src/utils/survey.js, src/views/DashboardView/StudentDashboard/SubjectSelection/PresessionSurvey.vue, src/views/FeedbackView.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/467
Description
-----------
- New student feedback view and questions
=> Postsession survey

src/views/StudentPartnerSignupView.vue
Description
-----------
- student must enter college or high school if the option is selected, regardless if a school is required during sign up
=> must enter school when option selected

src/components/Admin/FeedbackPreview.vue, src/components/App/AppModal/ModalTemplate.vue, src/services/NetworkService.js, src/store/modules/user.js, src/utils/survey.js, src/views/DashboardView/StudentDashboard/SubjectSelection/PresessionSurvey.vue, src/views/DashboardView/StudentDashboard/SubjectSelection/SubjectCard.vue, src/views/DashboardView/StudentDashboard/SubjectSelection/SubjectSelectionModal.vue, src/views/DashboardView/StudentDashboard/index.vue, src/views/FeedbackView.vue, src/views/SessionView/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/466
Description
-----------
- Add pre-session survey
- Add post-session survey
=> Session surveys

src/views/DashboardView/StudentDashboard/SubjectSelection/SubjectSelectionModal.vue
Description
-----------
- Update subject selection modal text from `choose a college subject` -> `choose a college counseling subject`
- Added spacing for the `title` for mobile devices
=> college subject -> college counseling subject

src/views/DashboardView/VolunteerDashboard/ListSessions.vue
Description
-----------
- Adds the amount of time a student has been waiting for a tutor to the `Waiting Students` table on the volunteer dashboard
- Poll for open sessions to update the wait time when there is at least one open session
=> add wait time to student waiting list

src/views/DashboardView/VolunteerDashboard/index.vue
Description
-----------
- UPdated the copy for the UPchieve 101 banner that displays on the volunteer dashboard for accounts that have been created before the UPchieve 101 course was created
=> update copy for upchieve 101 banner

src/services/AuthService.js, src/views/LoginView.vue
Description
-----------
- Fixes `Cannot read property 'then' of undefined` in `LoginView.vue` error
=> must provide login credentials to submit form

src/components/Admin/SessionFlags.vue, src/components/Admin/SessionListItem.vue, src/router.js, src/services/NetworkService.js, src/views/Admin/AdminSessionDetail.vue, src/views/Admin/AdminSessionReview.vue, src/views/Admin/index.vue, src/views/FeedbackView.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/503
Description
-----------
- Display a session's flags on the session review page and on the session detail page
- Update session when clicked `reviewed student` or `reviewed volunteer` via admin panel
Steps to test:
- Start a session as a student
- Join the session as a volunteer in another browser or in private mode via the same browser
- Send less than 20 messages, report the session, give low feedback and leave a comment on either both or on one user
- Make sure that your volunteer account has `isAdmin` set to `true`
- Visit Admin on the side panel > Session Review 
- The recent session should have flags appearing with the reasons why the session is marked to be reviewed
- Click on “Reviewed Student” and/or …
=> Session review

src/views/DashboardView/VolunteerDashboard/ReferencesModal.vue
Description
-----------
- Added a link to the reference guide in the references modal
=> add reference guide link to references modal

src/views/DashboardView/VolunteerDashboard/ListSessions.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/506
Description
-----------
- Hide sessions that list on the dashboard from banned volunteers
=> hide sessions from banned volunteers

src/views/SessionView/SessionHeader.vue
Description
-----------
- Fixes issue with trouble connecting modal showing if a student refreshes a session when already paired with a volunteer
=> add check for session volunteer

src/views/FeedbackView.vue
Description
-----------
- Check if `other` exists on `responseData.primary-goal` before using `toLowerCase()`
=> check if other exists on primary-goal object before toLowerCase()

.env.production, .env.staging
Description
-----------
- Update to the latest version of Zwibbler
=> updated zwibbler url

src/components/Admin/PendingVolunteerListItem.vue, src/components/ReferenceForm.vue, src/router.js, src/services/NetworkService.js, src/views/Admin/AdminPendingVolunteers.vue, src/views/Admin/index.vue, src/views/DashboardView/VolunteerDashboard/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/508
Description
-----------
- List of volunteers waiting to be reviewed now have a column of `Waiting since` instead of `Joined`
- Check if the reference exists before allowing them to submit the reference form
=> Update volunteer review

src/components/FormFooter.vue, src/views/LoginView.vue, src/views/SignupView/StudentForm.vue, src/views/SignupView/VolunteerForm.vue, src/views/SignupView/index.vue
Links
-----
- Issue: https://github.com/UPchieve/web/issues/546
Description
-----------
- Additional ARIA roles and landmarks, including those for signup forms
- The Lighthouse audit simply looks for an ARIA landmark and passes if it finds one; it isn't smart enough to give any thought to whether it is actually helping people with assistive technologies. Hence, the intended goal of this PR is to improve actual accessibility, not to improve the Lighthouse score.
=> Accessibility of form pages

src/views/SessionView/Whiteboard.vue
Description
-----------
- Access underlying web socket connection from Zwibbler 
=> update zwibbler ws connection

src/views/Admin/AdminSessionDetail.vue, src/views/SessionView/Whiteboard.vue
Description
-----------
- Fixes Zwibbler error `setViewRect: width and height must be non-zero.`
=> fix "setViewRect: width and height must be non-zero."

src/router.js, src/services/NetworkService.js, src/views/Admin/AdminZipCodes.vue, src/views/Admin/index.vue
Links
-----
- Server repo PR: https://github.com/UPchieve/server/pull/522
Description
-----------
- Lookup a zip code and get the eligibility and median income via the admin panel
=> Admin zip code

src/components/ButtonTemplate.vue, src/components/ReferenceForm.vue
Links
-----
- Issue: https://github.com/UPchieve/web/issues/546
Description
-----------
- Accessibility-related and validation-related changes to the `ReferenceForm` component
- Table elements are organized to comply with W3C guidelines
- `legend` element is added to `fieldset`
=> Reference form accessibility

src/components/App/AppHeader/DefaultHeader/index.vue, src/components/App/AppHeader/SessionHeader.vue, src/components/App/AppSidebar/SidebarInfo.vue
Links
-----
- Issue: https://github.com/UPchieve/web/issues/546
Description
-----------
- I merged in several commits from `html-validate` when I wanted the `app-sidebar-accessibility` branch to be reviewed first, as `html-validate` still shows some errors such as those having to do with not recognizing custom element names that should be recognized as non-issues; these custom elements need to be set in `.htmlvalidate.json`. For now, these commits are ready for review.
From old PR:
- Improving accessibility of app sidebar and headers by including alt text in images. The user avatars will have alt="" specified explicitly rather than simply missing the alt attribute.
=> App sidebar and header accessibility

src/views/DashboardView/StudentDashboard/SubjectSelection/index.vue
Description
-----------
- Allow students to request help in Physics 1
=> remove physicsOne from being temporarily hidden subjects

src/views/ProfileView.vue
Description
-----------
- Fix error: `Can't find variable: Notification` by first checking if `Notification` is supported 
=> check for Notification support before accessing permission
